### ISSUE TITLE
Authorship of the gem

### ISSUE THREAD

**Issue by huynhquancam** [bigbinary/docebo_ruby#2]
Hi @bigbinary,

Great to see you guys like my `docebo` gem. I'm also glad that BigBinary started taking on the maintenance of this gem.

Anyway, it would be much better if you guys could officially fork from my repo at https://github.com/huynhquancam/docebo_ruby.

Best,
Cam

**Comment by rkr090** [comment]
@huynhquancam 

Since the branch tip ( master ) of both repos has diverged, would it be ok if I add you as the original author with a link to your repo in README file ?

Really thanks for the gem.

**Comment by huynhquancam** [comment]
@rkr090 

That'll be great! Thank you!

**Comment by rkr090** [comment]
Added in https://github.com/bigbinary/docebo_ruby/commit/13d590a84ba22dbf3b2ced31b2f9a75db459140f
